spring:
    profiles.active: dev
    jmx.enabled: false
    main:
        banner-mode: off
        lazy-initialization: true
    data.mongodb.uri: mongodb://mongodb/sledger-investments
server.error.include-message: always
logging.level:
    org.springframework:
        boot: ERROR
        data: ERROR
        context: ERROR
    org.apache: ERROR
    org.mongodb: ERROR
saxo:
    uri: https://gateway.saxobank.com/sim/openapi
    auth-uri: https://sim.logonvalidation.net
    app-key: x
    app-secret: x
    redirect-uri: http://localhost:8080/token
