name: Release

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
        cache-dependency-path: web/yarn.lock
    - run: cd web && yarn && yarn build && cp -r dist ../src/main/resources/static/

    - uses: actions/setup-java@v1
      with:
        java-version: 17
    - uses: gradle/gradle-build-action@v2
    - run: ./gradlew build

    - id: tag
      run: |
        export TIMESTAMP=`date +'%Y%m%d%H%M'`
        echo "IMAGE_NAME=${{ SECRETS.DOCKER_REGISTRY }}/${{ SECRETS.DEPLOYMENT_NAME }}:$TIMESTAMP" >> $GITHUB_ENV
        echo "::set-output name=tag::$TIMESTAMP"

    - uses: docker/setup-buildx-action@v2

    - uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: docker/setup-qemu-action@v2

    - uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: ${{ env.IMAGE_NAME }}

  release:
    needs: build
    runs-on: self-hosted
    env:
      DEPLOYMENT: ${{ SECRETS.DEPLOYMENT_NAME }}
      IMAGE_NAME: ${{ SECRETS.DOCKER_REGISTRY_INT }}/${{ SECRETS.DEPLOYMENT_NAME }}:${{ needs.build.outputs.tag }}
    steps:
      - name: Perform rolling update
        run: |
          kubectl set image deploy/${DEPLOYMENT} ${DEPLOYMENT}=${IMAGE_NAME}
          kubectl rollout status deploy/${DEPLOYMENT}
